name: PR Update Notification

on:
  pull_request:
    types:
      - synchronize

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install required libraries for TLS support
        run: sudo apt-get update && sudo apt-get install -y libnet-ssleay-perl libio-socket-ssl-perl

      - name: Install sendemail package
        run: sudo apt-get update && sudo apt-get install -y sendemail

      - name: Fetch the list of closed pull requests
        run: |
          # Replace 'your_username', 'your_repo', and 'access_token' with your GitHub details
          username='cbhavya09'
          repository='working-sonata/integration-teams'
          access_token='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'

          # Construct the API endpoint URL to list pull requests (closed only)
          api_url="https://api.github.com/repos/$username/$repository/pulls?state=closed"

          # Prepare the headers with the personal access token for authentication
          headers="-H 'Authorization: Bearer $access_token' -H 'Accept: application/vnd.github.v3+json'"

          # Send the API request to get the list of closed pull requests
          closed_pull_requests=$(curl -s $headers $api_url)

          # Get the previous state of closed pull requests (you need to implement this logic)
          # For simplicity, assume we have a list called 'previous_state' containing pull request details.

          # Compare the current and previous state to detect updates
          if [[ "$closed_pull_requests" != "$previous_state" ]]; then
            echo "Closed PR updated. Trigger email notification."
            # Send the email using sendemail with TLS
            echo "Subject: GitHub PR Update Notification\nA closed Pull Request was updated. Check your GitHub repository for details." \
            | sendemail -f c.bhavya@sonata-software.com -t c.bhavya@sonata-software.com -s outlook.office365.com -o tls=yes -xu c.bhavya@sonata-software.com -xp Varshu@456
            echo "$closed_pull_requests" > previous_state.json
            exit 0
          fi

          echo "No updates to closed PRs."
          exit 1

      - name: Save the previous state for the next run
        run: echo "$closed_pull_requests" > previous_state.json
