name: PR Update Notification

on:
  push:
    branches:
      - main  # Replace with the branch name you want to monitor for updates

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Check for PR updates
        id: check_updates
        run: |
          # Create the previous_state.json file if it does not exist
          if [[ ! -f previous_state.json ]]; then
            echo "[]" > previous_state.json
          fi

          # Fetch the list of closed pull requests
          closed_pull_requests=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                                "https://api.github.com/repos/cbhavya09/working-sonata/integration-teams/pulls?state=closed")

          # Get the previous state of closed pull requests
          previous_state=$(cat previous_state.json)

          # Compare the current and previous state to detect updates
          if [[ "$closed_pull_requests" != "$previous_state" ]]; then
            echo "Closed PR updated. Trigger email notification."
            echo "$closed_pull_requests" > previous_state.json
            exit 0
          fi

          echo "No updates to closed PRs."
          exit 1

      - name: Send notification email
        if: steps.check_updates.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RECIPIENT_EMAIL: c.bhavya@sonata-software.com
        run: |
          echo "Subject: GitHub PR Update Notification\nA closed Pull Request was updated. Check your GitHub repository for details." | \
            mail -s "GitHub PR Update Notification" ${{ env.RECIPIENT_EMAIL }}
