name: PR Update Notification

on:
  pull_request:
    types:
      - reopened
      - synchronize
jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification email
        uses: actions/github-script@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RECIPIENT_EMAIL: c.bhavya@sonata-software.com
        with:
          script: |
            const EMAIL_CONTENT = "A closed Pull Request was updated. Check your GitHub repository for details.";
            const EMAIL_SUBJECT = "GitHub PR Update Notification";
            const MAIL_COMMAND = `echo "${EMAIL_CONTENT}" | mail -s "${EMAIL_SUBJECT}" ${{ env.RECIPIENT_EMAIL }}`;
            require('child_process').execSync(MAIL_COMMAND);
